local Store = require("tasko.store")
local Path = require("plenary.path")
local Task = require("tasko.task")

describe("Store", function()
	it("writes a task to json", function()
		local file = Store:write(Task:new(1, "title", "my description", 4, false))
		local task = Store:get_task_from_path(file)
		assert(task.id == 1, "id could not be read")
		assert(task.title == "title", "title could not be read")
		assert(task.description == "my description", "description could not be read")
		assert(task.priority == 4, "priority could not be read")
		assert(task.is_completed == false, "is_completed could not be read")
		Path:new(file):rm()
	end)
end)
